In [1]:
import numpy as np

In [2]:
array=np.array([1,2,3,4])

In [3]:
print(array, type(array), array.dtype, array.shape, array.size, array.ndim)

[1 2 3 4] <class 'numpy.ndarray'> int32 (4,) 4 1


In [4]:
arr2=np.array([
    [1,2,3,4],
    [5,6,7,8]
])

In [5]:
arr3=np.array([[
    [1,2,3,4],
    [5,6,7,8],
    [3,4,5,6]
],[
    [9,8,7,6],
    [5,4,3,2],
    [5,4,3,2]
]])

In [6]:
aar4=np.zeros((2,3))

In [7]:
print(aar4)

[[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
arr5=np.zeros((3,3,4))

In [9]:
print(arr5)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [10]:
arr6=np.ones((2,3))

In [11]:
print(arr6)

[[1. 1. 1.]
 [1. 1. 1.]]


In [12]:
arr7=np.ones((3,4,5))

In [13]:
print(arr7)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [113]:
arr8=np.arange(2,50,.3)

In [114]:
print(arr8)

[ 2.   2.3  2.6  2.9  3.2  3.5  3.8  4.1  4.4  4.7  5.   5.3  5.6  5.9
  6.2  6.5  6.8  7.1  7.4  7.7  8.   8.3  8.6  8.9  9.2  9.5  9.8 10.1
 10.4 10.7 11.  11.3 11.6 11.9 12.2 12.5 12.8 13.1 13.4 13.7 14.  14.3
 14.6 14.9 15.2 15.5 15.8 16.1 16.4 16.7 17.  17.3 17.6 17.9 18.2 18.5
 18.8 19.1 19.4 19.7 20.  20.3 20.6 20.9 21.2 21.5 21.8 22.1 22.4 22.7
 23.  23.3 23.6 23.9 24.2 24.5 24.8 25.1 25.4 25.7 26.  26.3 26.6 26.9
 27.2 27.5 27.8 28.1 28.4 28.7 29.  29.3 29.6 29.9 30.2 30.5 30.8 31.1
 31.4 31.7 32.  32.3 32.6 32.9 33.2 33.5 33.8 34.1 34.4 34.7 35.  35.3
 35.6 35.9 36.2 36.5 36.8 37.1 37.4 37.7 38.  38.3 38.6 38.9 39.2 39.5
 39.8 40.1 40.4 40.7 41.  41.3 41.6 41.9 42.2 42.5 42.8 43.1 43.4 43.7
 44.  44.3 44.6 44.9 45.2 45.5 45.8 46.1 46.4 46.7 47.  47.3 47.6 47.9
 48.2 48.5 48.8 49.1 49.4 49.7]


In [123]:
arr9=np.linspace(1,10,10)

In [124]:
print(arr9)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [34]:
arr10=np.linspace(10,100,10)

In [35]:
print(arr10)

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [67]:
arr10=np.eye(5,5,k=-1)

In [68]:
print(arr10)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [75]:
arr11=np.random.rand(4,2,5)

In [76]:
print(arr11)

[[[0.2375267  0.66763759 0.33163921 0.86989365 0.72830975]
  [0.66824026 0.71857566 0.13448318 0.20801828 0.93413758]]

 [[0.93679768 0.40062965 0.52443266 0.10735967 0.06870673]
  [0.69965894 0.52487961 0.22781338 0.8992973  0.07400968]]

 [[0.89116492 0.84204746 0.06182275 0.25489026 0.81786174]
  [0.74008658 0.9829351  0.77464274 0.22015978 0.30439155]]

 [[0.1490166  0.85730439 0.83687028 0.62458851 0.84032859]
  [0.3993636  0.62097726 0.20857627 0.08085093 0.89884933]]]


In [100]:
arr12=np.random.seed(43)
arr12=np.random.rand(4)
print(arr12)

[0.11505457 0.60906654 0.13339096 0.24058962]


In [102]:
arr12=np.random.seed(42)
arr12=np.random.rand(4)
print(arr12)

[0.37454012 0.95071431 0.73199394 0.59865848]


In [103]:
print(arr12)

[0.37454012 0.95071431 0.73199394 0.59865848]


In [168]:
arr13=np.random.seed(0)
arr13=np.random.randint(0,10, size=(3,3,3))
print(arr13)

[[[5 0 3]
  [3 7 9]
  [3 5 2]]

 [[4 7 6]
  [8 8 1]
  [6 7 7]]

 [[8 1 5]
  [9 8 9]
  [4 3 0]]]


In [169]:
print(arr13[1,2,1])

7


In [170]:
print(arr13[0:, 1:2, 1:2])

[[[7]]

 [[8]]

 [[8]]]


In [171]:
print(arr13[arr13%2==0])

[0 2 4 6 8 8 6 8 8 4 0]


In [172]:
print('\noriginal')
print(arr13)
print('\nfancy')
print(arr13[[0]])


original
[[[5 0 3]
  [3 7 9]
  [3 5 2]]

 [[4 7 6]
  [8 8 1]
  [6 7 7]]

 [[8 1 5]
  [9 8 9]
  [4 3 0]]]

fancy
[[[5 0 3]
  [3 7 9]
  [3 5 2]]]


In [173]:
print(arr13[0][[2,2,2]], arr13[1][[1,0,2]])  # its outpur will confuse you

[[3 5 2]
 [3 5 2]
 [3 5 2]] [[8 8 1]
 [4 7 6]
 [6 7 7]]


In [174]:
a=arr13[0][[2,1,0]]
b=arr13[1][[0,2,1]]
print(f'array 13 0 index array\n {a}\nArray 13 index 1 array\n{b}')

array 13 0 index array
 [[3 5 2]
 [3 7 9]
 [5 0 3]]
Array 13 index 1 array
[[4 7 6]
 [6 7 7]
 [8 8 1]]


In [175]:
arr14=np.random.seed(1)
arr14=np.random.randint(11,20, size=(3,3,3))
print(arr14)

[[[16 19 16]
  [11 11 12]
  [18 17 13]]

 [[15 16 13]
  [15 13 15]
  [18 18 12]]

 [[18 11 17]
  [18 17 12]
  [11 12 19]]]


In [176]:
print(arr13+arr14)

[[[21 19 19]
  [14 18 21]
  [21 22 15]]

 [[19 23 19]
  [23 21 16]
  [24 25 19]]

 [[26 12 22]
  [27 25 21]
  [15 15 19]]]


In [177]:
arr15=np.random.seed(2)
arr15=np.random.randint(21,30, size=(3,3))
print(arr15)

[[29 29 27]
 [23 29 28]
 [23 22 26]]


In [182]:
print(f'sum of arr15\n{arr15}\n and arr14 \n{arr14}\n is \n ==')
print(arr15+arr14)

sum of arr15
[[29 29 27]
 [23 29 28]
 [23 22 26]]
 and arr14 
[[[16 19 16]
  [11 11 12]
  [18 17 13]]

 [[15 16 13]
  [15 13 15]
  [18 18 12]]

 [[18 11 17]
  [18 17 12]
  [11 12 19]]]
 is 
 ==
[[[45 48 43]
  [34 40 40]
  [41 39 39]]

 [[44 45 40]
  [38 42 43]
  [41 40 38]]

 [[47 40 44]
  [41 46 40]
  [34 34 45]]]


In [184]:
arr16=np.random.seed(2)
arr16=np.random.randint(31,40, size=(3,3))

arr17=np.array([2,3])

In [185]:
print(f'arr16 {arr16}\n +\n arr17 {arr17}\n == \n {arr16+arr17} ')

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

In [186]:
print(arr16+arr17)

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

In [188]:
print(np.sin(arr17))

[0.90929743 0.14112001]


In [189]:
print(arr14.sum())

403


In [190]:
print(arr14.mean())

14.925925925925926


In [192]:
print(arr14.max())

19


In [193]:
print(arr14.min())

11


In [196]:
print(arr14,'\n')
print(arr14.cumsum())

[[[16 19 16]
  [11 11 12]
  [18 17 13]]

 [[15 16 13]
  [15 13 15]
  [18 18 12]]

 [[18 11 17]
  [18 17 12]
  [11 12 19]]] 

[ 16  35  51  62  73  85 103 120 133 148 164 177 192 205 220 238 256 268
 286 297 314 332 349 361 372 384 403]


In [197]:
print(arr14.ptp())

8
