In [1]:
import numpy as np

In [2]:
list1=[22,12,34,54,56]
array1=np.array([22,12,34,45,56])

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [7]:
array1.ndim

1

In [8]:
array1.shape

(5,)

In [9]:
array1.dtype

dtype('int32')

In [10]:
array1*2

array([ 44,  24,  68,  90, 112])

In [11]:
array2=np.array([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ],
    [
        [10,11,12],
        [13,14,15],
        [17,18,19]
    ],
    [
        [20,21,23],
        [24,25,26],
        [27,28,29]
    ]
])

In [12]:
print(array2)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [17 18 19]]

 [[20 21 23]
  [24 25 26]
  [27 28 29]]]


In [13]:
array2.ndim

3

In [14]:
array2.shape

(3, 3, 3)

In [15]:
array2.size

27

In [16]:
array1

array([22, 12, 34, 45, 56])

In [17]:
array1[1:3]

array([12, 34])

In [18]:
array2[1][2][1]

18

In [19]:
a='king'
b=123
c=[34,54,56]

In [20]:
array3=np.array(c)

In [21]:
print(array3)

[34 54 56]


In [22]:
list2=['king', 2,3,'ring']

In [23]:
array4=np.array(list2)

In [24]:
print(array4)

['king' '2' '3' 'ring']


In [99]:
value=int(input())
try:
    print(int(array4[value]))
except ValueError:
    print(array4[value])
except IndexError:
    print('enter proper index')

 kk


ValueError: invalid literal for int() with base 10: 'kk'

In [103]:
try:
    value = int(input("Enter index: "))
    try:
        print(int(array4[value]))
    except ValueError:
        print(array4[value])

except ValueError:
    print("Index must be a number")

except IndexError:
    print("Index out of range")


Enter index:  11


Index out of range


In [26]:
nums=[]

In [27]:
for x in list2:
    try:
        nums.append(int(x))
    except:
        pass

In [28]:
nums

[2, 3]

In [29]:
data = ['1e3', 'NaN', 'inf','3']

In [30]:
for x in data:
    try:
        val=float(x)
        if not (val==float('inf') or val==float('-inf') or val!=val):
            nums.append(val)
    except:
        pass

In [31]:
data

['1e3', 'NaN', 'inf', '3']

In [32]:
for x in data:
    try:
        nums.append(float(x))
    except:
        pass

In [33]:
nums

[2, 3, 1000.0, 3.0, 1000.0, nan, inf, 3.0]

In [34]:
nums=[]

In [35]:
for x in data:
    if isinstance(x, (int, float)):
        val=float(x)
        nums.append(val)
    elif isinstance(x, str):
        if x.isdigit():
            nums.append(val)

In [36]:
nums

[3.0]

In [37]:
array1

array([22, 12, 34, 45, 56])

In [38]:
sum(array1)

169

In [39]:
array55=np.array(['1', '2', '3', '4'])

##### array55 = array55.astype(int)

In [41]:
np.sum(array55)

10

In [42]:
np.max(array55)

4

In [43]:
np.argmax(array55)

3

In [44]:
#| Function      | Use           |
#| ------------- | ------------- |
#| `np.max()`    | Maximum value |
#| `np.min()`    | Minimum value |
#| `np.argmax()` | Index of max  |
#| `np.argmin()` | Index of min  |
#| `np.nanmax()` | Ignore NaN    |
#| `np.nanmin()` | Ignore NaN    |
#| `axis=0`      | Column wise   |
#| `axis=1`      | Row wise      |


In [45]:
data = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [5,  25, 35]
])

print(np.max(data))   # 60
print(np.min(data))   # 5


60
5


In [46]:
print(np.max(data, axis=0))  # Column-wise max


[40 50 60]


In [47]:
print(np.max(data, axis=1))  # Row-wise max



[30 60 35]


In [48]:
print(np.min(data, axis=0))


[ 5 20 30]


In [49]:
print(np.min(data, axis=1))


[10 40  5]


In [50]:
expenses = np.array([
    [200, 150, 300, 250, 400],   # Food
    [100, 120, 90, 110, 130],    # Travel
    [300, 400, 200, 350, 500]    # Shopping
])

print("Total Expense:", np.sum(expenses))
print("Category Wise Total:", np.sum(expenses, axis=1))
print("Day Wise Total:", np.sum(expenses, axis=0))

# Highest expense day
print("Highest Expense Day:", np.max(np.sum(expenses, axis=0)))

Total Expense: 3600
Category Wise Total: [1300  550 1750]
Day Wise Total: [ 600  670  590  710 1030]
Highest Expense Day: 1030


In [51]:
marks = np.array([45, 78, 88, 32, 90, 67, 55])

print("All Marks:", marks)

# Average
avg = np.mean(marks)
print("Average Marks:", avg)

# Pass students
passed = marks[marks >= 40]
print("Passed Students:", passed)

# Topper
topper = np.max(marks)
print("Topper Marks:", topper)

# Grades
grades = np.where(marks >= 75, "A",
          np.where(marks >= 60, "B",
          np.where(marks >= 40, "C", "Fail")))

print("Grades:", grades)

All Marks: [45 78 88 32 90 67 55]
Average Marks: 65.0
Passed Students: [45 78 88 90 67 55]
Topper Marks: 90
Grades: ['C' 'A' 'A' 'Fail' 'A' 'B' 'C']


In [52]:
arr = np.array([1, 4, 9, 16])

print(np.sqrt(arr))
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))


[1. 2. 3. 4.]
30
7.5
16
1


In [53]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print(a + b)
print(a - b)
print(a * b)
print(a / b)


[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]


In [54]:
result = np.where(marks >= 60, "Pass", "Fail")
print(result)


['Fail' 'Pass' 'Pass' 'Fail' 'Pass' 'Pass' 'Fail']


In [55]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[[0, 2, 4]])


[10 30 50]


In [56]:
print(marks[(marks > 40) & (marks < 80)])


[45 78 67 55]


In [57]:
marks = np.array([45, 67, 89, 32, 76])

print(marks > 60)
print(marks[marks > 60])


[False  True  True False  True]
[67 89 76]


In [59]:
data

array([[10, 20, 30],
       [40, 50, 60],
       [ 5, 25, 35]])

In [61]:
np.sum(data, axis=0)  # column wise

array([ 55,  95, 125])

In [60]:
np.sum(data, axis=1)  # row wise

array([ 60, 150,  65])

In [62]:
np.std(data)

16.905693394114376

In [64]:
np.mean(data)

30.555555555555557

In [69]:
data2=np.array([5,4,3,2,6,7])

In [70]:
np.std(data2)

1.707825127659933

In [71]:
array1

array([22, 12, 34, 45, 56])

In [72]:
array2

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [17, 18, 19]],

       [[20, 21, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [74]:
array11=np.array([2,3,4])

In [76]:
arra22=np.array([
    [2],
    [3],
    [4]
])

In [77]:
array11*array2

array([[[  2,   6,  12],
        [  8,  15,  24],
        [ 14,  24,  36]],

       [[ 20,  33,  48],
        [ 26,  42,  60],
        [ 34,  54,  76]],

       [[ 40,  63,  92],
        [ 48,  75, 104],
        [ 54,  84, 116]]])

In [80]:
array2

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [17, 18, 19]],

       [[20, 21, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [79]:
arra22*array2

array([[[  2,   4,   6],
        [ 12,  15,  18],
        [ 28,  32,  36]],

       [[ 20,  22,  24],
        [ 39,  42,  45],
        [ 68,  72,  76]],

       [[ 40,  42,  46],
        [ 72,  75,  78],
        [108, 112, 116]]])

In [81]:
%timeit arr * 2

809 ns ± 9.32 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [83]:
%timeit [i*2 for i in arr]

1.03 μs ± 8.9 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [84]:
import time

start = time.perf_counter()

for _ in range(1, 1000):
    pass

end = time.perf_counter()
print(end - start)


0.0014612001832574606


In [104]:
import time

start = time.perf_counter()

for i in range(1, 10):
    print(i)

end = time.perf_counter()
print("Total time:", end - start)


1
2
3
4
5
6
7
8
9
Total time: 0.00045419996604323387


In [86]:
arr = np.array([10, 25, 30, 5, 8])

print(arr[arr > 10])


[25 30]


In [87]:
result = []
for i in arr:
    result.append(i * 2)


In [88]:
result = arr * 2


In [89]:
arr = np.array([[1,2,3],
                [4,5,6]])

print(arr.sum(axis=0))  # column-wise
print(arr.sum(axis=1))  # row-wise


[5 7 9]
[ 6 15]


In [90]:
arr = np.array([1, 4, 9])

print(np.sqrt(arr))
print(np.log(arr))
print(np.exp(arr))


[1. 2. 3.]
[0.         1.38629436 2.19722458]
[2.71828183e+00 5.45981500e+01 8.10308393e+03]


In [91]:
arr = np.array([10, 5, 20, 3])

new = np.where(arr > 10, arr * 2, arr)
print(new)


[10  5 40  3]


In [92]:
a = np.array([1,2])
b = np.array([3,4])

print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 2]
 [3 4]]
[1 2 3 4]


In [93]:
arr = np.array([1,2,3,4,5,6])
print(np.split(arr, 3))

[array([1, 2]), array([3, 4]), array([5, 6])]


In [94]:
arr = np.array([[1,2],[3,4]])

arr.reshape(4,1)
arr.ravel()    # view
arr.flatten()  # copy

array([1, 2, 3, 4])

In [95]:
np.random.seed(42)
data = np.random.normal(0, 1, (1000, 2))