In [1]:
import numpy as np

In [2]:
list1=[22,12,34,54,56]
array1=np.array([22,12,34,45,56])

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [6]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [13]:
array1.ndim

1

In [14]:
array1.shape

(5,)

In [15]:
array1.dtype

dtype('int32')

In [16]:
array1*2

array([ 44,  24,  68,  90, 112])

In [17]:
array2=np.array([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ],
    [
        [10,11,12],
        [13,14,15],
        [17,18,19]
    ],
    [
        [20,21,23],
        [24,25,26],
        [27,28,29]
    ]
])

In [18]:
print(array2)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [17 18 19]]

 [[20 21 23]
  [24 25 26]
  [27 28 29]]]


In [19]:
array2.ndim

3

In [20]:
array2.shape

(3, 3, 3)

In [24]:
array2.size

27

In [26]:
array1

array([22, 12, 34, 45, 56])

In [28]:
array1[1:3]

array([12, 34])

In [32]:
array2[1][2][1]

18

In [33]:
a='king'
b=123
c=[34,54,56]

In [34]:
array3=np.array([a,b,c])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [35]:
array3=np.array(c)

In [36]:
print(array3)

[34 54 56]


In [37]:
list2=['king', 2,3,'ring']

In [38]:
array4=np.array(list2)

In [39]:
print(array4)

['king' '2' '3' 'ring']


In [54]:
value=int(input())
try:
    print(int(array4[value]))
except ValueError:
    print(array4[value])
except IndexError:
    print('enter proper index')

 0


king


In [90]:
nums=[]

In [57]:
for x in list2:
    try:
        nums.append(int(x))
    except:
        pass

In [58]:
nums

[2, 3]

In [87]:
data = ['1e3', 'NaN', 'inf','3']

In [85]:
for x in data:
    try:
        val=float(x)
        if not (val==float('inf') or val==float('-inf') or val!=val):
            nums.append(val)
    except:
        pass

In [64]:
data

['1e3', 'NaN', 'inf']

In [72]:
for x in data:
    try:
        nums.append(float(x))
    except:
        pass

In [86]:
nums

[1000.0]

In [98]:
nums=[]

In [99]:
for x in data:
    if isinstance(x, (int, float)):
        val=float(x)
        nums.append(val)
    elif isinstance(x, str):
        if x.isdigit():
            nums.append(val)

In [100]:
nums

[3.0]

In [102]:
array1

array([22, 12, 34, 45, 56])

In [103]:
sum(array1)

169

In [104]:
array55=np.array(['1', '2', '3', '4'])

In [106]:
np.sum(array55)

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U1'), dtype('<U1')) -> None

In [107]:
array55 = array55.astype(int)

In [108]:
np.sum(array55)

10

In [110]:
np.max(array55)

4

In [111]:
np.argmax(array55)

3

In [112]:
#| Function      | Use           |
#| ------------- | ------------- |
#| `np.max()`    | Maximum value |
#| `np.min()`    | Minimum value |
#| `np.argmax()` | Index of max  |
#| `np.argmin()` | Index of min  |
#| `np.nanmax()` | Ignore NaN    |
#| `np.nanmin()` | Ignore NaN    |
#| `axis=0`      | Column wise   |
#| `axis=1`      | Row wise      |


In [113]:
data = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [5,  25, 35]
])

print(np.max(data))   # 60
print(np.min(data))   # 5


60
5


In [115]:
print(np.max(data, axis=0))  # Column-wise max


[40 50 60]


In [116]:
print(np.max(data, axis=1))  # Row-wise max



[30 60 35]


In [117]:
print(np.min(data, axis=0))


[ 5 20 30]


In [118]:
print(np.min(data, axis=1))


[10 40  5]


In [119]:
expenses = np.array([
    [200, 150, 300, 250, 400],   # Food
    [100, 120, 90, 110, 130],    # Travel
    [300, 400, 200, 350, 500]    # Shopping
])

print("Total Expense:", np.sum(expenses))
print("Category Wise Total:", np.sum(expenses, axis=1))
print("Day Wise Total:", np.sum(expenses, axis=0))

# Highest expense day
print("Highest Expense Day:", np.max(np.sum(expenses, axis=0)))

Total Expense: 3600
Category Wise Total: [1300  550 1750]
Day Wise Total: [ 600  670  590  710 1030]
Highest Expense Day: 1030


In [120]:
marks = np.array([45, 78, 88, 32, 90, 67, 55])

print("All Marks:", marks)

# Average
avg = np.mean(marks)
print("Average Marks:", avg)

# Pass students
passed = marks[marks >= 40]
print("Passed Students:", passed)

# Topper
topper = np.max(marks)
print("Topper Marks:", topper)

# Grades
grades = np.where(marks >= 75, "A",
          np.where(marks >= 60, "B",
          np.where(marks >= 40, "C", "Fail")))

print("Grades:", grades)

All Marks: [45 78 88 32 90 67 55]
Average Marks: 65.0
Passed Students: [45 78 88 90 67 55]
Topper Marks: 90
Grades: ['C' 'A' 'A' 'Fail' 'A' 'B' 'C']


In [121]:
arr = np.array([1, 4, 9, 16])

print(np.sqrt(arr))
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))


[1. 2. 3. 4.]
30
7.5
16
1


In [122]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print(a + b)
print(a - b)
print(a * b)
print(a / b)


[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]


In [123]:
result = np.where(marks >= 60, "Pass", "Fail")
print(result)


['Fail' 'Pass' 'Pass' 'Fail' 'Pass' 'Pass' 'Fail']


In [124]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[[0, 2, 4]])


[10 30 50]


In [125]:
print(marks[(marks > 40) & (marks < 80)])


[45 78 67 55]


In [126]:
marks = np.array([45, 67, 89, 32, 76])

print(marks > 60)
print(marks[marks > 60])


[False  True  True False  True]
[67 89 76]
