In [15]:
import pandas as pd

In [8]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd
from scipy.stats import f_oneway

In [9]:
from scipy.stats import chi2_contingency

In [10]:
import numpy as np

In [11]:
from scipy import stats

In [3]:
data = [65, 75, 60, 80, 70]

In [4]:
t_stat, p_value = stats.ttest_1samp(data, 70.5)

In [5]:
print("t-value:", t_stat)
print("p-value:", p_value)

t-value: -0.1414213562373095
p-value: 0.8943736167296328


In [6]:
alpha=0.05

In [7]:
if p_value < alpha:
    print("Reject H0")
else:
    print("Fail to Reject H0")

Fail to Reject H0


In [8]:
percentage = p_value * 100

In [9]:
print(percentage)

89.43736167296328


In [10]:
A = [60, 65, 70]
B = [75, 80, 85]
C = [62, 68, 66]

In [11]:
a=np.array(A)
b=np.array(B)
c=np.array(C)

In [12]:
print(np.mean(a))
print(np.mean(b))
print(np.mean(c))

65.0
80.0
65.33333333333333


In [13]:
F_stat, p_value = stats.f_oneway(A, B, C)

In [14]:
print("F-value:", F_stat)
print("p-value:", p_value)

F-value: 11.129213483146078
p-value: 0.009572156773558516


In [15]:
if p_value < alpha:
    print("Reject H0 → At least one group mean is different")
else:
    print("Fail to Reject H0 → All group means are statistically similar")

Reject H0 → At least one group mean is different


In [16]:
data_chi = np.array([[40,60],
                 [10,90]])

chi2, p, dof, expected = stats.chi2_contingency(data)

print("Chi-square:", chi2)
print("p-value:", p)

Chi-square: 0.0
p-value: 1.0


In [17]:
Data=np.array(data)

In [18]:
np.std(Data)

7.0710678118654755

In [19]:
np.var(Data)

50.0

In [20]:
std_error = stats.sem(data)

In [21]:
print(std_error)

3.5355339059327373


In [22]:
data

[65, 75, 60, 80, 70]

In [26]:
data = np.array([
    [30, 10, 10],   # Online
    [15, 25, 10],   # Offline
    [35,  5, 10]    # Hybrid
])

In [27]:
chi2, p, dof, expected = stats.chi2_contingency(data)

print("Chi-square value:", chi2)
print("p-value:", p)
print("Degrees of freedom:", dof)
print("Expected values:\n", expected)

Chi-square value: 24.374999999999996
p-value: 6.717357689248024e-05
Degrees of freedom: 4
Expected values:
 [[26.66666667 13.33333333 10.        ]
 [26.66666667 13.33333333 10.        ]
 [26.66666667 13.33333333 10.        ]]


In [28]:
if p < alpha:
    print("Reject H0 → Relation exists")
else:
    print("Fail to Reject H0 → No strong relation")

Reject H0 → Relation exists


In [4]:
# Observed frequency table
observed = np.array([
    [20, 15, 15],   # School
    [30, 10, 10],   # Graduate
    [25, 20, 5]     # Postgraduate
])


In [5]:
chi2, p, dof, expected = chi2_contingency(observed)

In [6]:
print("Chi-Square Value:", chi2)
print("p-value:", p)
print("Degrees of Freedom:", dof)
print("Expected Frequencies:\n", expected)

Chi-Square Value: 10.333333333333334
p-value: 0.03517188548771231
Degrees of Freedom: 4
Expected Frequencies:
 [[25. 15. 10.]
 [25. 15. 10.]
 [25. 15. 10.]]


In [7]:
n = observed.sum()
k = min(observed.shape)  # smaller of rows or columns

cramers_v = np.sqrt(chi2 / (n * (k - 1)))

print("Cramer's V:", cramers_v)


Cramer's V: 0.1855921454276674


In [12]:
group_A = [65, 75, 60, 80]
group_B = [80, 75, 85, 92]
group_C = [68, 65, 70, 73]

In [13]:
f_stat, p_value = f_oneway(group_A, group_B, group_C)

print("F-value:", f_stat)
print("p-value:", p_value)


F-value: 4.968325791855204
p-value: 0.03517441988702211


In [16]:
data = group_A + group_B + group_C
groups = (["A"]*4 + ["B"]*4 + ["C"]*4)

df = pd.DataFrame({
    "score": data,
    "group": groups
})

In [17]:
tukey = pairwise_tukeyhsd(endog=df["score"],
                          groups=df["group"],
                          alpha=0.05)

print(tukey)


 Multiple Comparison of Means - Tukey HSD, FWER=0.05 
group1 group2 meandiff p-adj   lower    upper  reject
-----------------------------------------------------
     A      B     13.0  0.065  -0.8354 26.8354  False
     A      C     -1.0 0.9779 -14.8354 12.8354  False
     B      C    -14.0 0.0475 -27.8354 -0.1646   True
-----------------------------------------------------


In [19]:
data = group_A + group_B + group_C

In [20]:
groups = (["A"]*4 + ["B"]*4 + ["C"]*4)

In [21]:
tukey = pairwise_tukeyhsd(data, groups, alpha=0.05)

In [22]:
print(tukey)

 Multiple Comparison of Means - Tukey HSD, FWER=0.05 
group1 group2 meandiff p-adj   lower    upper  reject
-----------------------------------------------------
     A      B     13.0  0.065  -0.8354 26.8354  False
     A      C     -1.0 0.9779 -14.8354 12.8354  False
     B      C    -14.0 0.0475 -27.8354 -0.1646   True
-----------------------------------------------------
