# Statistical Tests in Python
Includes:
- One Sample T-Test (with Confidence Interval)
- Independent T-Test
- Paired T-Test
- ANOVA
- Correlation
- Chi-Square Test
- Linear Regression
- Outliers (Z-Score & IQR)


## 1️⃣ One Sample T-Test (Manual + CI)

In [1]:

import numpy as np
from scipy import stats

data = [22, 25, 19, 24, 23, 27, 21, 26]
mu_0 = 20

n = len(data)
mean = np.mean(data)
std = np.std(data, ddof=1)

t_stat = (mean - mu_0) / (std / np.sqrt(n))
p_value = 2 * (1 - stats.t.cdf(abs(t_stat), df=n-1))

confidence = 0.95
t_critical = stats.t.ppf((1 + confidence) / 2, df=n-1)
margin_error = t_critical * (std / np.sqrt(n))

lower = mean - margin_error
upper = mean + margin_error

print("Sample Mean:", mean)
print("T-statistic:", t_stat)
print("P-value:", p_value)
print("95% Confidence Interval:", (lower, upper))
print("t critical:- ",t_critical)
print("margin error:- ",margin_error)

Sample Mean: 23.375
T-statistic: 3.5762373640756184
P-value: 0.009021395149089395
95% Confidence Interval: (21.14343479985606, 25.60656520014394)
t critical:-  2.3646242515927844
margin error:-  2.2315652001439408


In [2]:
t_stat, p_value = stats.ttest_1samp(data, mu_0)
print(t_stat, p_value)
if p_value < 0.05:
    print("Conclusion: Significant Difference")
else:
    print("Conclusion: No Significant Difference")

3.5762373640756184 0.009021395149089447
Conclusion: Significant Difference


## 2️⃣ Independent T-Test

In [3]:

group1 = [10, 12, 14, 16, 18]
group2 = [8, 9, 11, 13, 15]

t_stat, p_value = stats.ttest_ind(group1, group2)

print("T-stat:", t_stat)
print("P-value:", p_value)

if p_value < 0.05:
    print("Conclusion: Significant Difference")
else:
    print("Conclusion: No Significant Difference")

T-stat: 1.467598771410686
P-value: 0.18039544877850114
Conclusion: No Significant Difference


In [4]:
import numpy as np
from scipy import stats

group1 = np.array([10, 12, 14, 16, 18])
group2 = np.array([8, 9, 11, 13, 15])

n1 = len(group1)
n2 = len(group2)

mean1 = np.mean(group1)
mean2 = np.mean(group2)

std1 = np.std(group1, ddof=1)
std2 = np.std(group2, ddof=1)

# Pooled SD
sp = np.sqrt(((n1-1)*std1**2 + (n2-1)*std2**2) / (n1+n2-2))

se = sp * np.sqrt(1/n1 + 1/n2)

t_stat = (mean1 - mean2) / se
df = n1 + n2 - 2
p_value = 2 * (1 - stats.t.cdf(abs(t_stat), df=df))

confidence = 0.95
t_critical = stats.t.ppf((1 + confidence) / 2, df=df)
margin_error = t_critical * se

lower = (mean1 - mean2) - margin_error
upper = (mean1 - mean2) + margin_error

# -------- Clean Output --------

print("Mean Difference:", round(mean1 - mean2, 2))
print("T-statistic:", round(t_stat, 3))
print("P-value:", round(p_value, 3))
print("95% Confidence Interval:", (round(lower,2), round(upper,2)))

if p_value < 0.05:
    print("Conclusion: Significant Difference")
else:
    print("Conclusion: No Significant Difference")

Mean Difference: 2.8
T-statistic: 1.468
P-value: 0.18
95% Confidence Interval: (-1.6, 7.2)
Conclusion: No Significant Difference


## 3️⃣ Paired T-Test

In [21]:


before = np.array([10, 12, 14, 16, 18])
after  = np.array([12, 14, 15, 18, 20])

before_mean=np.mean(before)

after_mean=np.mean(after)

t_stat, p_value = stats.ttest_rel(before, after)

print("T-stat:", t_stat)
print("P-value:", p_value)

if p_value < 0.05:
    print("Conclusion: Significant Difference")
else:
    print("Conclusion: No Significant Difference")

print (f"before mean {before_mean} and aftermean {after_mean}")


T-stat: -9.0
P-value: 0.0008438325176012782
Conclusion: Significant Difference
before mean 14.0 and aftermean 15.8


## 4️⃣ One-Way ANOVA

In [22]:

import numpy as np
from scipy import stats

# -----------------------------
# Step 1: Define Groups
# -----------------------------
group1 = np.array([10, 12, 14])
group2 = np.array([15, 17, 19])
group3 = np.array([20, 22, 24])

# -----------------------------
# Step 2: Calculate Means
# -----------------------------
mean1 = np.mean(group1)
mean2 = np.mean(group2)
mean3 = np.mean(group3)

print("Group 1 Mean:", mean1)
print("Group 2 Mean:", mean2)
print("Group 3 Mean:", mean3)

# -----------------------------
# Step 3: Perform One-Way ANOVA
# -----------------------------
f_stat, p_value = stats.f_oneway(group1, group2, group3)

print("\n===== ANOVA RESULT =====")
print("F-statistic:", round(f_stat, 4))
print("P-value:", round(p_value, 4))

# -----------------------------
# Step 4: Interpretation
# -----------------------------
alpha = 0.05

if p_value < alpha:
    print("\nConclusion: At least one group mean is significantly different.")
else:
    print("\nConclusion: No significant difference among group means.")

Group 1 Mean: 12.0
Group 2 Mean: 17.0
Group 3 Mean: 22.0

===== ANOVA RESULT =====
F-statistic: 18.75
P-value: 0.0026

Conclusion: At least one group mean is significantly different.


In [23]:
import numpy as np
import pandas as pd
from scipy import stats
from statsmodels.stats.multicomp import pairwise_tukeyhsd

# -----------------------------
# Step 1: Define Groups
# -----------------------------
group1 = [10, 12, 14]
group2 = [15, 17, 19]
group3 = [20, 22, 24]

# -----------------------------
# Step 2: Combine Data
# -----------------------------
data = group1 + group2 + group3

labels = (["Group1"] * len(group1) +
          ["Group2"] * len(group2) +
          ["Group3"] * len(group3))

df = pd.DataFrame({
    "values": data,
    "groups": labels
})

# -----------------------------
# Step 3: Perform Tukey HSD
# -----------------------------
tukey = pairwise_tukeyhsd(endog=df["values"],
                          groups=df["groups"],
                          alpha=0.05)

print("===== Tukey HSD Results =====")
print(tukey)

===== Tukey HSD Results =====
Multiple Comparison of Means - Tukey HSD, FWER=0.05 
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
Group1 Group2      5.0 0.0504 -0.0105 10.0105  False
Group1 Group3     10.0 0.0021  4.9895 15.0105   True
Group2 Group3      5.0 0.0504 -0.0105 10.0105  False
----------------------------------------------------


## 5️⃣ Pearson Correlation

In [24]:
import numpy as np
from scipy import stats

# -----------------------------
# Step 1: Define Data
# -----------------------------
x = np.array([1,2,3,4,5])
y = np.array([2,5,7,10,11])

# -----------------------------
# Step 2: Perform Pearson Correlation
# -----------------------------
corr, p_value = stats.pearsonr(x, y)

print("===== Pearson Correlation Result =====")
print("Correlation Coefficient (r):", round(corr, 4))
print("P-value:", round(p_value, 4))

# -----------------------------
# Step 3: Interpretation
# -----------------------------
alpha = 0.05

if p_value < alpha:
    print("\nConclusion: Significant Linear Relationship exists.")
else:
    print("\nConclusion: No Significant Linear Relationship.")

===== Pearson Correlation Result =====
Correlation Coefficient (r): 0.9898
P-value: 0.0012

Conclusion: Significant Linear Relationship exists.


## 6️⃣ Chi-Square Test

In [25]:
import numpy as np
from scipy.stats import chi2_contingency

# ----------------------------------
# Step 1: Create Contingency Table
# ----------------------------------
table = np.array([
    [10, 20, 30],
    [6,  9,  17]
])

print("Observed Frequencies:\n", table)

# ----------------------------------
# Step 2: Perform Chi-Square Test
# ----------------------------------
chi2, p, dof, expected = chi2_contingency(table)

print("\n===== Chi-Square Test Result =====")
print("Chi-square Statistic:", round(chi2, 4))
print("P-value:", round(p, 4))
print("Degrees of Freedom:", dof)

print("\nExpected Frequencies:\n", np.round(expected, 2))

# ----------------------------------
# Step 3: Effect Size (Cramer's V)
# ----------------------------------
n = table.sum()
k = min(table.shape)

cramers_v = np.sqrt(chi2 / (n * (k - 1)))

print("\nCramer's V:", round(cramers_v, 4))

# ----------------------------------
# Step 4: Hypothesis Interpretation
# ----------------------------------
alpha = 0.05

if p < alpha:
    print("\nConclusion: Significant relationship exists between variables.")
else:
    print("\nConclusion: No significant relationship between variables.")

# ----------------------------------
# Step 5: Strength Interpretation
# ----------------------------------
if cramers_v < 0.1:
    strength = "Very Weak"
elif cramers_v < 0.3:
    strength = "Weak"
elif cramers_v < 0.5:
    strength = "Moderate"
else:
    strength = "Strong"

print("Strength of Association:", strength)

Observed Frequencies:
 [[10 20 30]
 [ 6  9 17]]

===== Chi-Square Test Result =====
Chi-square Statistic: 0.2716
P-value: 0.873
Degrees of Freedom: 2

Expected Frequencies:
 [[10.43 18.91 30.65]
 [ 5.57 10.09 16.35]]

Cramer's V: 0.0543

Conclusion: No significant relationship between variables.
Strength of Association: Very Weak


## 7️⃣ Linear Regression

Predicted y for x=6: 5.8


## 8️⃣ Outliers using Z-Score

In [26]:
import numpy as np
from scipy import stats

# -----------------------------
# Step 1: Define Data
# -----------------------------
x = np.array([1,2,3,4,5])
y = np.array([2,4,5,4,5])

# -----------------------------
# Step 2: Perform Linear Regression
# -----------------------------
slope, intercept, r_value, p_value, std_err = stats.linregress(x, y)

print("Slope (m):", round(slope, 4))
print("Intercept (c):", round(intercept, 4))
print("R-value:", round(r_value, 4))
print("R-squared:", round(r_value**2, 4))
print("P-value:", round(p_value, 4))

# -----------------------------
# Step 3: Prediction
# -----------------------------
x_new = 6
y_pred = intercept + slope * x_new

print("\nPredicted y for x=6:", round(y_pred, 3))

Slope (m): 0.6
Intercept (c): 2.2
R-value: 0.7746
R-squared: 0.6
P-value: 0.124

Predicted y for x=6: 5.8


## 9️⃣ Outliers using IQR

In [27]:
import numpy as np

# -----------------------------
# Step 1: Define Data
# -----------------------------
data = np.array([10, 12, 14, 15, 100])

# -----------------------------
# Step 2: Calculate Quartiles
# -----------------------------
Q1 = np.percentile(data, 25)
Q3 = np.percentile(data, 75)
IQR = Q3 - Q1

print("Q1 (25th percentile):", Q1)
print("Q3 (75th percentile):", Q3)
print("IQR:", IQR)

# -----------------------------
# Step 3: Define Bounds
# -----------------------------
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Lower Bound:", lower_bound)
print("Upper Bound:", upper_bound)

# -----------------------------
# Step 4: Detect Outliers
# -----------------------------
outliers = data[(data < lower_bound) | (data > upper_bound)]

print("\nOutliers (IQR method):", outliers)

Q1 (25th percentile): 12.0
Q3 (75th percentile): 15.0
IQR: 3.0
Lower Bound: 7.5
Upper Bound: 19.5

Outliers (IQR method): [100]


In [28]:
import numpy as np

# -----------------------------
# Step 1: Define Data
# -----------------------------
data = np.array([10, 12, 14, 15, 100])

# -----------------------------
# Step 2: Calculate Median
# -----------------------------
median = np.median(data)

# -----------------------------
# Step 3: Calculate MAD
# MAD = Median(|xi - median|)
# -----------------------------
mad = np.median(np.abs(data - median))

# -----------------------------
# Step 4: Calculate Modified Z-Score
# Formula:
# 0.6745 * (xi - median) / MAD
# -----------------------------
modified_z_scores = 0.6745 * (data - median) / mad

# -----------------------------
# Step 5: Detect Outliers
# Threshold = 3.5
# -----------------------------
outliers = data[np.abs(modified_z_scores) > 3.5]

print("Median:", median)
print("MAD:", mad)
print("Modified Z-Scores:", np.round(modified_z_scores, 3))
print("Outliers:", outliers)

Median: 14.0
MAD: 2.0
Modified Z-Scores: [-1.349 -0.674  0.     0.337 29.004]
Outliers: [100]
